i18nc("Game board name", "Empty - Small");
i18nc("Game board name", "Empty - Medium");
i18nc("Game board name", "Empty - Large");
i18nc("Game board name", "Columns");
i18nc("Game board name", "Corridor");
i18nc("Game board name", "Island");
i18nc("Game board name", "Rocks");
i18nc("Game board name", "Spiral");
i18nc("Game board name", "Trees");
i18nc("Game board name", "Walls");
i18nc("Game board name", "Empty - Small");
i18nc("Game board name", "Empty - Medium");
i18nc("Game board name", "Empty - Large");
i18nc("Game board name", "Columns");
i18nc("Game board name", "Corridor");
i18nc("Game board name", "Island");
i18nc("Game board name", "Rocks");
i18nc("Game board name", "Spiral");
i18nc("Game board name", "Trees");
i18nc("Game board name", "Walls");
